# -*- coding: utf-8 -*-
"""US Accidents Exploratory Data Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15lo3NVaGM_S5Q9dpFDs9yaU877EbxV4k

#US Accidents Exploratory Data Analysis
"""

!pip install jovian --upgrade -q

import jovian
jovian.set_project('us-accidents-analysis')
jovian.set_colab_id('3d425c76e1e437d840227c77ac0774a9')

pip install opendatasets --upgrade --quiet

import opendatasets as od
dataset_url = 'https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents'
od.download('https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents')

data_filename = './us-accidents/US_Accidents_Dec21.csv'

#DATA PREPARATION AND CLEANING

#load the file using pandas 
#look at some information about the data & columbs
#fix any missing or incorrect values

import pandas as pd

df = pd.read_csv(data_filename)

df

df.columns

df.info()

df.describe()

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
numeric_df = df.select_dtypes(include=numerics)
len(numeric_df.columns)

"""Percentage of missing value per colunm"""

missing_percentages = df.isna().sum().sort_values(ascending=False) / len(df)
missing_percentages

missing_percentages[missing_percentages !=0]

missing_percentages.plot()

missing_percentages[missing_percentages !=0].plot(kind='barh')



"""Remove columns that you don't want to use"""



"""Exploratory Analysis and visualization"""

df.columns

df.City

cities = df.City.unique()
len(cities)

cities = df.City.unique()
cities[:100]

cities_by_accident = df.City.value_counts()
cities_by_accident

cities_by_accident[:20]

'NY' in df.State

cities_by_accident[:10].plot(kind='barh')

